#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(light > 40){
			motor[motorA] = 100;
			wait1Msec(400);
		}
		motor[motorA] = -100;
		motor[motorB] = -100;
	}
}
